name: Perform CICD Operations on Console Based Java App
on: push
jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Config Tools(JAVA, MVN)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: 2. Provision Tools(Terraform)
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: 3. Check Java and Maven Versions
        run: |
          java -version
          javac -version
          mvn --version
          terraform --version

      - name: 4. Clone Project
        uses: actions/checkout@v3     

      - name: 5. Clean Project
        run: mvn clean

      - name: 6. Build ,Test and Packaging Project
        run: mvn package 
      
      - name: 7. Infrastructure Provisioning(Initialize)
        run: terraform init

      - name: 8. Infrastructure Provisioning(Plan)
        run: terraform plan 

      - name: 9. Infrastructure Provisioning(Apply)
        run: terraform apply -auto-approve -input=false

      - name: 10. Deploy and Run Project
        run: |
          cd target

          export AWS_ACCESS_KEY_ID=AKIASMJSK6OY2YJ5H65A
          export AWS_SECRET_ACCESS_KEY=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
          export AWS_DEFAULT_REGION=us-east-1
          aws s3 ls 
          aws s3 cp Tomcat-DeployWAR.war s3://bkt-vishal-final